FROM golang:1.24

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    vim \
    less \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m -s /bin/bash $USERNAME \
    && chown -R $USERNAME:$USERNAME /home/$USERNAME


WORKDIR /workspace

USER $USERNAME

CMD [ "bash" ]
