FROM golang:1.24

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    vim \
    less \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m -s /bin/bash $USERNAME \
    && chown -R $USERNAME:$USERNAME /home/$USERNAME

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

WORKDIR /workspace

USER $USERNAME

CMD [ "bash" ]
