// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/internal/adapters/rest/handlers"
	"app/internal/adapters/rest/routes"
	"app/internal/drivers/restserver"
	"log/slog"
)

// Injectors from wire.go:

func SetupApp() (*App, error) {
	logger := slog.Default()
	handlerFactory := handlers.NewHandlerFactory(logger)
	router := routes.NewRouter(handlerFactory, logger)
	server := restserver.NewServerFromConfig(router)
	app := NewApp(server, logger)
	return app, nil
}
