// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/internal/adapters/rest/handlers"
	"app/internal/adapters/rest/routes"
	"app/internal/drivers/otel"
	"app/internal/drivers/restserver"
	"app/internal/drivers/wireproviders"
	"log/slog"
)

// Injectors from wire.go:

func SetupApp() (*App, error) {
	logger := slog.Default()
	handlerFactory := handlers.NewHandlerFactory(logger)
	v := wireproviders.ProvideMiddlewares()
	router := routes.NewRouter(handlerFactory, v)
	server := restserver.NewServerFromConfig(router)
	tracerProviderShutdown, err := otel.SetupOtel()
	if err != nil {
		return nil, err
	}
	app := NewApp(server, logger, tracerProviderShutdown)
	return app, nil
}
