// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_routes

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHandlerFactory creates a new instance of HandlerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerFactory {
	mock := &HandlerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HandlerFactory is an autogenerated mock type for the HandlerFactory type
type HandlerFactory struct {
	mock.Mock
}

type HandlerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *HandlerFactory) EXPECT() *HandlerFactory_Expecter {
	return &HandlerFactory_Expecter{mock: &_m.Mock}
}

// UploadFile provides a mock function for the type HandlerFactory
func (_mock *HandlerFactory) UploadFile() http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// HandlerFactory_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type HandlerFactory_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
func (_e *HandlerFactory_Expecter) UploadFile() *HandlerFactory_UploadFile_Call {
	return &HandlerFactory_UploadFile_Call{Call: _e.mock.On("UploadFile")}
}

func (_c *HandlerFactory_UploadFile_Call) Run(run func()) *HandlerFactory_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HandlerFactory_UploadFile_Call) Return(handler http.Handler) *HandlerFactory_UploadFile_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *HandlerFactory_UploadFile_Call) RunAndReturn(run func() http.Handler) *HandlerFactory_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
